name: Python application

on:
  repository_dispatch:
    types: [on-map-update]
  schedule:
    - cron:  '0 21 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: MLS
      run: |
        sudo apt update
        sudo apt install libxml2-utils
        sudo apt install gzip
        curl -sS https://location.services.mozilla.com/downloads | xmllint --html --xpath 'string(/html/body/div/section/ul/li[1]/a/@href)' - | xargs -n 1 curl -s | gzip -d | awk 'BEGIN{FS=","; OFS=","} ($1 == "LTE" && $2 == 440 && $3 == 11 && $5 >= 188743680 && $5 < 190023680 && $6 != "" && $9 > 0) {print $4,$5,$6,$7,$8,$9,$10,$12,$13}' > mls_44011.csv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python main.py
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./map
        publish_branch: gh-pages
